# Site settings
title: zyuzhi
header-img: "img/louvre_pyramid.jpg"
tagline: "zyuzhi"  
description: "随心"  
baseurl: ""
url: "http://zyuzhi.me"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "zyuzhi"
  email: zyuzhi78@gmail.cn
  bio: "随心"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: /img/favicon.ico

#douban_username: 
twitter_username: zyuzhi
github_username: zyuzhi  
#facebook_username: 
weibo_username: yuzhi在上海
zhihu_username: z.yuzhi  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    table_class: z-code-table
    gutter_class: z-code-gutter
    code_class: z-code-col
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

highlighter: rouge
line_numbers: true

gems: 
#- jekyll-gallery-generator
- jekyll-paginate
- jekyll-seo-tag
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "zyuzhi"
      header-img: "img/road.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : zyuzhi
  disqus :
      short_name : zyuzhi

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
